### ISSUE TITLE
index error with filtered dataset

### ISSUE THREAD

**Issue by inkyusa** [inkyusa/BuilT#1]
Index error raises from here https://github.com/inkyusa/BuilT/blob/9e163f903624f9c82e29b53393bcfda09cd305f9/tweet/src/tweet_dataset.py#L99 with the attached filtered dataset.
@jlim262 Could you please have a look at this?
[train_corrected.zip](https://github.com/inkyusa/BuilT/files/5613362/train_corrected.zip)

**Comment by jlim262** [comment]
It comes out if there is an empty 'selected_text' in the dataset. Check out this line of dataset. 
792063a20e,    _Geronimo    Thanks for sharing with your friends!,  ,positive

We need to remove those lines from the dataset. 

Can you fix it from correct_dataset.py?
